"""Initial schema - users, applications, predictions, audit_logs, metrics

Revision ID: 196a9b156de2
Revises: 
Create Date: 2025-10-20 04:08:43.817833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196a9b156de2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_metrics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('period_minutes', sa.Integer(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=True),
    sa.Column('cache_misses', sa.Integer(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('avg_cache_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_db_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_keys', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('evictions', sa.Integer(), nullable=True),
    sa.Column('expirations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_timestamp', 'cache_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cache_metrics_timestamp'), 'cache_metrics', ['timestamp'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('total_predictions', sa.Integer(), nullable=True),
    sa.Column('total_approvals', sa.Integer(), nullable=True),
    sa.Column('total_rejections', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('avg_profitability_score', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('total_loan_amount', sa.Float(), nullable=True),
    sa.Column('avg_loan_amount', sa.Float(), nullable=True),
    sa.Column('detailed_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_period_end', 'model_metrics', ['period_end'], unique=False)
    op.create_index('idx_metrics_period_start', 'model_metrics', ['period_start'], unique=False)
    op.create_index('idx_metrics_type', 'model_metrics', ['period_type'], unique=False)
    op.create_index(op.f('ix_model_metrics_period_end'), 'model_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_model_metrics_period_start'), 'model_metrics', ['period_start'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_pincode'), 'users', ['pincode'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('loan_purpose', sa.String(length=255), nullable=False),
    sa.Column('loan_tenure_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sms_transactions', sa.JSON(), nullable=True),
    sa.Column('contact_metadata', sa.JSON(), nullable=True),
    sa.Column('location_pattern', sa.JSON(), nullable=True),
    sa.Column('behavioral_data', sa.JSON(), nullable=True),
    sa.Column('extracted_features', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_amount', 'applications', ['loan_amount'], unique=False)
    op.create_index('idx_app_status', 'applications', ['status'], unique=False)
    op.create_index('idx_app_submitted', 'applications', ['submitted_at'], unique=False)
    op.create_index('idx_app_user', 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_submitted_at'), 'applications', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_category', 'audit_logs', ['event_category'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_application_id'), 'audit_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_category'), 'audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_id', sa.String(length=100), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('decision_threshold', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('feature_contributions', sa.JSON(), nullable=True),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('prediction_latency_ms', sa.Float(), nullable=True),
    sa.Column('estimated_profitability_inr', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pred_app', 'predictions', ['application_id'], unique=False)
    op.create_index('idx_pred_decision', 'predictions', ['decision'], unique=False)
    op.create_index('idx_pred_score', 'predictions', ['profitability_score'], unique=False)
    op.create_index('idx_pred_timestamp', 'predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_predictions_application_id'), 'predictions', ['application_id'], unique=False)
    op.create_index(op.f('ix_predictions_decision'), 'predictions', ['decision'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_predictions_prediction_timestamp'), 'predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_predictions_profitability_score'), 'predictions', ['profitability_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_profitability_score'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_decision'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_application_id'), table_name='predictions')
    op.drop_index('idx_pred_timestamp', table_name='predictions')
    op.drop_index('idx_pred_score', table_name='predictions')
    op.drop_index('idx_pred_decision', table_name='predictions')
    op.drop_index('idx_pred_app', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_application_id'), table_name='audit_logs')
    op.drop_index('idx_audit_type', table_name='audit_logs')
    op.drop_index('idx_audit_request', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_category', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_submitted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_index('idx_app_user', table_name='applications')
    op.drop_index('idx_app_submitted', table_name='applications')
    op.drop_index('idx_app_status', table_name='applications')
    op.drop_index('idx_app_amount', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_pincode'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_metrics_period_start'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_period_end'), table_name='model_metrics')
    op.drop_index('idx_metrics_type', table_name='model_metrics')
    op.drop_index('idx_metrics_period_start', table_name='model_metrics')
    op.drop_index('idx_metrics_period_end', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_cache_metrics_timestamp'), table_name='cache_metrics')
    op.drop_index('idx_cache_timestamp', table_name='cache_metrics')
    op.drop_table('cache_metrics')
    # ### end Alembic commands ###
